### ISSUE TITLE
your Icons sucks

### ISSUE THREAD

**Issue by RGProgrammer** [apilayer/weatherstack#4]
i'm working on an app for a Hotel in flutter. the app uses WeatherStack Service( currently the free offer for testing) and i found that the weather icons sucks and does not go well with the theme colors in the app. So i decided to use Icons made in my company but the problem is i don't know all weather_discriptions or the each weather code to create/select an icon for each description/code. can you add more documentation about that.
btw: why weather_discriptions is a vector of string why not a single string using "_" instead of spaces?

**Comment by I-keep-trying** [comment]
@RGProgrammer I completely agree about the icons. 

There is a link in the documentation to download the weather codes [here](https://weatherstack.com/site_resources/weatherstack-weather-condition-codes.zip).

I came here to complain that the 'is_day' response seems to *always* say 'yes', regardless what country I query. So, even though I'm using my own icons, I guess I cannot provide day/night versions... disappointing.

**Comment by RGProgrammer** [comment]
my bad , sorry about that. anyway i already changed to another weather api (that offer a better pricing ) and using my own icons to go with the color theme of the app.

**Comment by I-keep-trying** [comment]
Cool, I'm also trying out other apis, only because I can't afford to pay right now and I already hit weatherstack's limit for the entire MONTH. 

But I also need to retract my statement about the 'is_day' parameter, that was my fault. I kept looking at the wrong response.
