### ISSUE TITLE
Historical Time Series data randomly drops days in series

### ISSUE THREAD

**Issue by Brando753** [apilayer/weatherstack#9]
I purchased the standard api membership to try and do some model analysis on historical humidity in a region and I noticed that I was missing days from the time series requested. I also noticed that if I re-ran the api call with the same inputs different days would be dropped. I was trying to get information from the 'Scottsdale, United States of America' region with time series requested for the following start/stop periods 
```
[
  ["2020-01-01", "2020-02-29"], 
  ["2020-03-01", "2020-04-29"], 
  ["2020-04-30", "2020-06-28"], 
  ["2020-06-29", "2020-08-27"], 
  ["2020-08-28", "2020-10-17"]
] 
```
Attached is the data received for those time series requests (extension of .txt so github would accept it)
Notice how in example one the historical dates go 2020-01-01 through 2020-01-13 then skip 14 and resume. Example two 
starts with 2020-01-01 through 2020-01-03 skips 4 has 5 skips 6...etc.

[github_example1.txt](https://github.com/apilayer/weatherstack/files/5398064/github_example1.txt)
[github_example2.txt](https://github.com/apilayer/weatherstack/files/5398065/github_example2.txt)

.

**Comment by johncourtlob** [comment]
We are also seeing this issue

**Comment by orinoco** [comment]
I'm seeing this too. If I ask for 2 days, eg. 2018-06-14 -> 2018-06-15, at any location, but let's use for example `query: 'Lat 51.00 and Lon -114.00'`, sometimes it gives me:

```
historical:
   { '2018-06-14':
      { date: '2018-06-14',
        date_epoch: 1528934400,
        astro: [Object],
        mintemp: 9,
        maxtemp: 13,
        avgtemp: 11,
        totalsnow: 0,
        sunhour: 14.8,
        uv_index: 4,
        hourly: [Array] } } }
```

and sometimes it gives me the correct answer:

```
  historical:
   { '2018-06-14':
      { date: '2018-06-14',
        date_epoch: 1528934400,
        astro: [Object],
        mintemp: 9,
        maxtemp: 13,
        avgtemp: 11,
        totalsnow: 0,
        sunhour: 14.8,
        uv_index: 4,
        hourly: [Array] },
     '2018-06-15':
      { date: '2018-06-15',
        date_epoch: 1529020800,
        astro: [Object],
        mintemp: 8,
        maxtemp: 19,
        avgtemp: 12,
        totalsnow: 0,
        sunhour: 14.8,
        uv_index: 4,
        hourly: [Array] } } }
```

I can repeat this just by issuing the request a few times over a few minutes. It happens for all our locations, and for bigger date periods too, randomly dropping dates.

**Comment by Brando753** [comment]
I contacted Weatherstack customer service in reference to the bug I reported here, they sent the following reply:
>Hi,
>
>We've deployed another fix for the problem.
>
>Please let us know if you are experiencing any further issues!
>
>Best regards
>
>Aleksa
>Customer Service

On my testing, it appears to have solved the issue, if one other person can confirm that they are no longer seeing the issue as reported I will close this bug report.

**Comment by orinoco** [comment]
It's been good for me too since the fix.

**Comment by Brando753** [comment]
Alright, good to hear! Closing the bug report then.
